name: build-push-container-image
on:
  push:
    branches:
    - master
jobs:
  build-push-container-image:
    runs-on: ubuntu-latest
    steps:
    - name: docker-hub-authenticate
      run: docker login --u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: docker-build
      run: docker build . -t merenze/auth-service:latest
    - name: docker-push
      run: docker push merenze/auth-service:latest