// models/user.js
const { Model, DataTypes } = require("sequelize");

class User extends Model {
  constructor(props) {
    super();
    Object.keys(props).forEach(key => {
      this[key] = props[key];
    });
  }
}

module.exports = (sequelize) => {
  User.init(
    {
      // Unique, autogenerated id
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      // Email address
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      // Hashed password
      passwordHash: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      // Time of email validation
      emailValidatedAt: DataTypes.DATE,
    },
    { sequelize }
  );
};
