// models/user.js
const { Model, DataTypes } = require("sequelize");

class User extends Model {
  /**
   * 
   * @param {string} email Email address of the user
   * @returns {Promise<User>} A promise resolving to the user with the email address.
   */
  static async findByEmail(email) {
    return this.findOne({ where: { email: email } });
  }
}

module.exports = (sequelize) => {
  User.init(
    {
      // Unique, autogenerated id
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      // Email address
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      // Hashed password
      passwordHash: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      // Time of email validation
      emailValidatedAt: DataTypes.DATE,
    },
    { sequelize }
  );
  return User;
};
